apiVersion: v1
kind: Secret
metadata:
  name: {{ include "content-hub.fullname" . }}-secrets
type: Opaque
stringData:
  session-secret: {{ required "secrets.sessionSecret is required" .Values.secrets.sessionSecret | quote }}
  azure-tenant-id: {{ .Values.secrets.azureTenantId | quote }}
  azure-client-id: {{ .Values.secrets.azureClientId | quote }}
  azure-client-secret: {{ .Values.secrets.azureClientSecret | quote }}
