apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plc-api.fullname" . | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: {{ include "plc-api.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "plc-api.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "plc-api.name" . }}
    spec:
      containers:
        - name: plc-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8081
          env:
            - name: PLC_HOST
              value: "127.0.0.1"
          resources: {{ toYaml .Values.resources | nindent 12 }}

