[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[build.buildArgs]
SERVICE_DIR = ""

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1
